name: Weekly English Progress Analysis

on:
  schedule:
    - cron: '0 9 * * 1'  # Se ejecuta cada lunes a las 9:00 AM
  workflow_dispatch:      # Permite ejecución manual

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create Weekly Report
      run: |
        echo "# Weekly English Progress Report" > progress/weekly-report.md
        echo "Generated on: $(date)" >> progress/weekly-report.md
        python scripts/track-progress.py >> progress/weekly-report.md
    
    - name: Create Issue
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('./progress/weekly-report.md', 'utf8');
          
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Weekly English Progress Report ${new Date().toISOString().split('T')[0]}`,
            body: report,
            labels: ['weekly-report']
          });