name: Weekly English Progress Analysis

on:
  schedule:
    - cron: '0 9 * * 1'  # Monday 9:00 AM
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib
    
    - name: Run analysis
      run: python scripts/track-progress.py
    
    - name: Create Weekly Report Issue
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('./progress/latest_report.md', 'utf8');
          
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Weekly English Progress Report ${new Date().toISOString().split('T')[0]}`,
            body: report,
            labels: ['weekly-report']
          });
